-- AlterTable
ALTER TABLE "Shop" ADD COLUMN     "bookAheadDays" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "closeTime" TEXT NOT NULL DEFAULT '21:00',
ADD COLUMN     "leadTime" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "openTime" TEXT NOT NULL DEFAULT '09:00',
ADD COLUMN     "slotInterval" INTEGER NOT NULL DEFAULT 15;
